import logging
from pathlib import Path
from llama_index.core.schema import Document

try:
    import easyocr
except ImportError:
    easyocr = None
    logging.warning(
        "easyocr not installed. Please install it to use EasyOcrProcessor: pip install easyocr"
    )


logger = logging.getLogger(__name__)

# Configuration for EasyOCR processing
# In a production environment, these should be loaded from a configuration file or environment variables.
EASY_OCR_ENABLED = True  # Master switch for this feature
EASY_OCR_LANGUAGES = ['en']  # Default languages for EasyOCR, e.g., ['en', 'ch_sim']
EASY_OCR_GPU = True  # Whether to use GPU for EasyOCR (if available and supported)
EASY_OCR_MODEL_STORAGE_DIRECTORY = None # Optional: Path to directory for model storage
EASY_OCR_USER_NETWORK_DIRECTORY = None # Optional: Path to directory for user network
EASY_OCR_DOWNLOAD_ENABLED = True # Optional: Enable/disable model auto-download

class EasyOcrProcessor:
    """
    Processes images using EasyOCR to extract text.
    """

    EASY_OCR_ENABLED = EASY_OCR_ENABLED  # <-- Add this line

    def __init__(
        self,
        languages: list[str] | None = None,
        gpu: bool = EASY_OCR_GPU,
        model_storage_directory: str | None = EASY_OCR_MODEL_STORAGE_DIRECTORY,
        user_network_directory: str | None = EASY_OCR_USER_NETWORK_DIRECTORY,
        download_enabled: bool = EASY_OCR_DOWNLOAD_ENABLED,
        enabled: bool = EASY_OCR_ENABLED,
    ):
        self.enabled = enabled
        self.reader = None
        self.languages = languages if languages is not None else EASY_OCR_LANGUAGES
        self.gpu = gpu
        self.model_storage_directory = model_storage_directory
        self.user_network_directory = user_network_directory
        self.download_enabled = download_enabled

        if not self.enabled:
            logger.info("EasyOCR Processor is disabled by configuration.")
            return

        if easyocr is None:
            logger.error("EasyOCR library is not installed. EasyOcrProcessor cannot function.")
            self.enabled = False
            return

        try:
            logger.info(
                f"Initializing EasyOCR Reader with languages: {self.languages}, GPU: {self.gpu}"
            )
            self.reader = easyocr.Reader(
                self.languages,
                gpu=self.gpu,
                model_storage_directory=self.model_storage_directory,
                user_network_directory=self.user_network_directory,
                download_enabled=self.download_enabled,
            )
            logger.info("EasyOCR Reader initialized successfully.")
        except Exception as e:
            logger.error(f"Failed to initialize EasyOCR Reader: {e}")
            self.enabled = False  # Disable if reader fails to initialize

    def load_data(self, file_path: Path, file_name: str) -> list[Document] | None:
        """
        Loads an image file, extracts text using EasyOCR, and returns a Document.
        Returns None if processing is disabled, fails, the file doesn't exist, or no text is found.
        """
        if not self.enabled or not self.reader:
            logger.debug(
                f"EasyOCR processing skipped for {file_name} (disabled or reader not initialized)."
            )
            return None

        if not file_path.exists():
            logger.error(f"File not found for EasyOCR processing: {file_path}")
            return None
        
        if not file_path.is_file():
            logger.error(f"Path is not a file, skipping EasyOCR: {file_path}")
            return None

        try:
            logger.info(f"Attempting to process image {file_name} with EasyOCR.")
            
            # EasyOCR's readtext method takes the image path as a string or bytes.
            # Using detail=0 returns only the text.
            # Using paragraph=True attempts to join text into paragraphs.
            ocr_results = self.reader.readtext(str(file_path), detail=0, paragraph=True)
            
            extracted_text = "\n".join(ocr_results).strip()

            if extracted_text:
                document = Document(
                    text=extracted_text,
                    metadata={
                        "file_name": file_name,
                        "source_model": "easyocr",
                        "ocr_languages": self.languages,
                        "processing_method": "easy_ocr_extraction"
                        # doc_id will be auto-generated by LlamaIndex
                    }
                )
                # Sanitize NUL bytes, though less likely from OCR
                document.text = document.text.replace("\x00", "").replace("\\u0000", "")
                logger.info(
                    f"Successfully processed image {file_name} with EasyOCR. Text length: {len(extracted_text)}"
                )
                return [document]
            else:
                logger.warning(f"EasyOCR processing for image {file_name} returned no text.")
                return None
        
        except Exception as e:
            logger.error(f"An error occurred processing image {file_name} with EasyOCR: {e}")
            return None
