\
import logging
from pathlib import Path
import base64
import requests
from llama_index.core.schema import Document

logger = logging.getLogger(__name__)

# Configuration for Ollama image processing
# In a production environment, these should be loaded from a configuration file or environment variables.
OLLAMA_IMAGE_PROCESSING_ENABLED = True  # Master switch for this feature
OLLAMA_API_URL = "http://localhost:11434/api/generate"  # Standard Ollama API endpoint for generate
OLLAMA_MODEL_NAME = "gemma3:12b"  # Default multimodal model for image processing
OLLAMA_IMAGE_PROMPT = "Analyse this image in detail. try to find numbers and texts with pin point accuracy"  # Prompt for Ollama
OLLAMA_REQUEST_TIMEOUT = 200 # Seconds

class OllamaImageProcessor:
    """
    Processes images using an Ollama multimodal model to generate descriptions.
    """

    def __init__(
        self,
        model_name: str = OLLAMA_MODEL_NAME,
        api_url: str = OLLAMA_API_URL,
        prompt: str = OLLAMA_IMAGE_PROMPT,
        timeout: int = OLLAMA_REQUEST_TIMEOUT,
        enabled: bool = OLLAMA_IMAGE_PROCESSING_ENABLED,
    ):
        self.model_name = model_name
        self.api_url = api_url
        self.prompt = prompt
        self.timeout = timeout
        self.enabled = enabled
        if not self.enabled:
            logger.info("Ollama Image Processor is disabled by configuration.")

    def load_data(self, file_path: Path, file_name: str) -> list[Document] | None:
        """
        Loads image data, sends it to Ollama for processing, and returns a Document.
        Returns None if processing is disabled, fails, or the response is empty.
        """
        if not self.enabled:
            return None

        try:
            logger.info(f"Attempting to process image {file_name} with Ollama model {self.model_name}")
            image_bytes = file_path.read_bytes()
            encoded_image = base64.b64encode(image_bytes).decode('utf-8')

            payload = {
                "model": self.model_name,
                "prompt": self.prompt,
                "images": [encoded_image],
                "stream": False  # Get the full response at once
            }
            
            response = requests.post(self.api_url, json=payload, timeout=self.timeout)
            response.raise_for_status()  # Raise an exception for HTTP errors (4xx or 5xx)
            
            ollama_response_json = response.json()
            ollama_response_text = ollama_response_json.get("response", "").strip()

            if ollama_response_text:
                document = Document(
                    text=ollama_response_text,
                    metadata={
                        "file_name": file_name,
                        "source_model": self.model_name,
                        "processing_method": "ollama_image_description"
                        # doc_id will be auto-generated by LlamaIndex
                    }
                )
                # Sanitize NUL bytes, though less likely in LLM output
                document.text = document.text.replace("\\\\u0000", "")
                logger.info(f"Successfully processed image {file_name} with Ollama. Response length: {len(ollama_response_text)}")
                return [document]
            else:
                logger.warning(f"Ollama processing for image {file_name} returned an empty response.")
                return None
        
        except requests.exceptions.Timeout:
            logger.error(f"Ollama API request timed out for image {file_name} after {self.timeout}s.")
            return None
        except requests.exceptions.RequestException as e:
            logger.error(f"Ollama API request failed for image {file_name}: {e}.")
            return None
        except Exception as e:
            logger.error(f"An unexpected error occurred processing image {file_name} with Ollama: {e}.")
            return None

